// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUKrravTRbDdo12RWCdaV2t5GhrqYEum8',
    appId: '1:876245014770:web:df6f1bc66b878aea7f186b',
    messagingSenderId: '876245014770',
    projectId: 'psiapoio-a6b92',
    authDomain: 'psiapoio-a6b92.firebaseapp.com',
    storageBucket: 'psiapoio-a6b92.firebasestorage.app',
    measurementId: 'G-PSWYF0CL22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfq6nGyxuB5ptI106uIBr4U_JjCTrhSeQ',
    appId: '1:876245014770:android:d183088e9d2e76fb7f186b',
    messagingSenderId: '876245014770',
    projectId: 'psiapoio-a6b92',
    storageBucket: 'psiapoio-a6b92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9gCqeawjOQf33xIXtJFv3u7fZQLPVQjI',
    appId: '1:876245014770:ios:df733809b8dc0a537f186b',
    messagingSenderId: '876245014770',
    projectId: 'psiapoio-a6b92',
    storageBucket: 'psiapoio-a6b92.firebasestorage.app',
    iosClientId: '876245014770-3sbk0jaao3efnbfnrcqbecer2ejchtf2.apps.googleusercontent.com',
    iosBundleId: 'com.example.psiapoio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9gCqeawjOQf33xIXtJFv3u7fZQLPVQjI',
    appId: '1:876245014770:ios:df733809b8dc0a537f186b',
    messagingSenderId: '876245014770',
    projectId: 'psiapoio-a6b92',
    storageBucket: 'psiapoio-a6b92.firebasestorage.app',
    iosClientId: '876245014770-3sbk0jaao3efnbfnrcqbecer2ejchtf2.apps.googleusercontent.com',
    iosBundleId: 'com.example.psiapoio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUKrravTRbDdo12RWCdaV2t5GhrqYEum8',
    appId: '1:876245014770:web:3ea9c2cfd4a9e5b37f186b',
    messagingSenderId: '876245014770',
    projectId: 'psiapoio-a6b92',
    authDomain: 'psiapoio-a6b92.firebaseapp.com',
    storageBucket: 'psiapoio-a6b92.firebasestorage.app',
    measurementId: 'G-TDFKK8SJS1',
  );
}
